### ISSUE TITLE
Doesn’t build on Linux x64?

### ISSUE THREAD

**Issue by emirotin** [abiliojr/fts5-snowball#4]
I’ve successfully built it on macOS but it errors on Linux with an error supposedly described here: https://stackoverflow.com/questions/7865059/why-does-gcc-force-pic-for-x64-shared-libs

**Comment by emirotin** [comment]
FYI I managed to compile it by adding `-fPIC` to both this modules `cc` calls **and the upstream snowball**: `CPPFLAGS=-Iinclude -fPIC`

**Comment by abiliojr** [comment]
Thanks for your feedback, I modified the Makefile to reflect your findings. See commit a41026855a52c505587b88c32835466db21fe44c

**Comment by emirotin** [comment]
Nice, will test and let you know how it works

**Comment by emirotin** [comment]
Yeah just made the fresh build and worked fine, also did a smoke test of the actual search. Thanks a lot.
Will check tomorrow that it still builds on Mac - just in case :)

**Comment by emirotin** [comment]
All good on MacOS too!
BTW do you have any experience building it for Windows (and not _depending on_ Cygwin / MinGW _presence on the user's system_)?
I'm working on cross-platform desktop app and this extension is the only platform-specific part

_UPD: corrected wording_
