### ISSUE TITLE
Core dump loading extension in sqlite 3.22

### ISSUE THREAD

**Issue by gpayo** [abiliojr/fts5-snowball#5]
I'm testing Ubuntu Bionic Beaver (18.04) who brings with SQLite 3.22.
I've compiled the extension, it only show this warning:
```
src/fts5stemmer.c: In function ‘fts5SnowballCb’:
src/fts5stemmer.c:243:10: warning: ‘stemmed’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   return p->xToken(p->pCtx, tflags, (char *) stemmed, nBuf, iStart, iEnd);
```
But it generates the `fts5stemmer.so` file anyways, but when I load it in sqlite3 command line it crash generating a core dump.

**Comment by abiliojr** [comment]
Fixed now. Thanks for reporting it and sorry for the delay
